# Teste de sintaxe do workflow
name: Build APK - Corte de Matos App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Tipo de build'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - development
          - production

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
